name: C# Lint

on:
  pull_request:
    paths:
      - "libraries/csharp/**"
      - ".github/workflows/csharp-lint.yml"

jobs:
  dotnet:
    name: C# Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: |
          dotnet build --configuration Release StandardWebhooks
        working-directory: libraries/csharp
