name: Csharp Lint

on:
  pull_request:
    paths:
      - "libraries/csharp/**"

jobs:
  dotnet:
    name: C# Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x

      - name: Install dependencies
        run: |
          cd libraries/csharp
          dotnet restore

      - name: Build
        run: |
          cd libraries/csharp
          dotnet build --configuration Release StandardWebhooks --no-restore
