name: JavaScript Release

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write

jobs:
  build:
    name: JavaScript Release
    runs-on: ubuntu-latest
    environment: Release

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v6
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install modules
        run: |
          yarn
        working-directory: libraries/javascript

      - name: Publish
        run: |
          npm publish --provenance
        working-directory: libraries/javascript
