name: Java Lint

on:
  pull_request:
    paths:
      - "libraries/java/**"
      - ".github/workflows/java-lint.yml"

jobs:
  build:
    name: Java Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Build
        run: |
          ./gradlew build
        working-directory: libraries/java
