name: JavaScript Lint

on:
  pull_request:
    paths:
      - "libraries/javascript/**"
      - ".github/workflows/javascript-lint.yml"

jobs:
  build:
    name: JavaScript Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v7
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Install modules
        run: |
          yarn
        working-directory: libraries/javascript

      - name: Lint
        run: |
          yarn run lint
        working-directory: libraries/javascript

      - name: Test
        run: |
          yarn test
        working-directory: libraries/javascript
