name: JavaScript Lint

on:
  pull_request:
    paths:
      - "libraries/javascript/**"
      - ".github/workflows/javascript-lint.yml"

jobs:
  build:
    name: JavaScript Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v7
        with:
          node-version: "24"

      - name: Install modules
        run: |
          npm ci
        working-directory: libraries/javascript

      - name: Lint
        run: |
          npm run check
        working-directory: libraries/javascript

      - name: Test
        run: |
          npm test
        working-directory: libraries/javascript
