name: Python Lint

on:
  pull_request:
    paths:
      - "libraries/python/**"
      - ".github/workflows/python-lint.yml"

jobs:
  build:
    name: Python Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt .
          python -m pip install -r requirements-dev.txt .
        working-directory: libraries/python

      - name: Run linting
        run: |
          sh ./scripts/lint.sh
        working-directory: libraries/python

      - name: Run test
        run: |
          pytest
        working-directory: libraries/python
