name: Python Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt .
          python -m pip install -r requirements-dev.txt .
        working-directory: libraries/python

      - name: Install setuptools
        run: |
          python -m pip install setuptools
        working-directory: libraries/python

      - name: Build sdist
        run: |
          python setup.py sdist
        working-directory: libraries/python

      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TWINE_PASSWORD }}
          packages_dir: libraries/python/dist
