name: Rust Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Hack around cargo stuff
        run: |
          git config user.email "work@around.com"
          git config user.name "Work Around"
          git add -f src/apis/ src/models/
          git commit -a -m "Snap"
        working-directory: libraries/rust

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: libraries/rust -> target

      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        working-directory: libraries/rust
